language: node_js
node_js:
- '6'
sudo: false
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  email: true
after_failure: cat /home/travis/build/rogerpadilla/angular2-minimalist-starter/npm-debug.log
branches:
  only:
  - master
env:
  global:
  # https://github.com/DefinitelyTyped/tsd#tsdrc
  # Token has no scope (read-only access to public information)
  - TSD_GITHUB_TOKEN=020041acfaefe6c423ee8d217eb732635f84dc5d
